// GF(256) arithmetic for QR Reed-Solomon error correction (ISO/IEC 18004 Annex A).
// Field is generated by the primitive polynomial x^8 + x^4 + x^3 + x^2 + 1 (0x11D),
// with 2 as the primitive element (generator).

const FIELD_SIZE = 256;
const PRIMITIVE_POLY = 0x11d;

// EXP[i] = 2^i in GF(256). Table is duplicated past index 254 so that
// EXP[log(a) + log(b)] never needs an extra modulo when multiplying.
export const EXP = new Uint8Array(512);
// LOG[a] = i such that 2^i = a, for a in [1, 255]. LOG[0] is unused.
export const LOG = new Uint8Array(256);

(function buildTables() {
  let x = 1;
  for (let i = 0; i < FIELD_SIZE - 1; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= PRIMITIVE_POLY;
  }
  for (let i = FIELD_SIZE - 1; i < EXP.length; i++) {
    EXP[i] = EXP[i - (FIELD_SIZE - 1)];
  }
})();

/** Multiply two elements of GF(256). */
export function gfMul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return EXP[LOG[a] + LOG[b]];
}

/** Divide a by b in GF(256). */
export function gfDiv(a: number, b: number): number {
  if (b === 0) throw new Error("division by zero in GF(256)");
  if (a === 0) return 0;
  return EXP[(LOG[a] - LOG[b] + 255) % 255];
}

/** Raise a to an integer power in GF(256). */
export function gfPow(a: number, power: number): number {
  if (a === 0) return power === 0 ? 1 : 0;
  const e = (((LOG[a] * power) % 255) + 255) % 255;
  return EXP[e];
}

/** Multiplicative inverse of a in GF(256). */
export function gfInverse(a: number): number {
  if (a === 0) throw new Error("0 has no inverse in GF(256)");
  return EXP[255 - LOG[a]];
}
